### ISSUE TITLE
Use fs.stats as a filter

### ISSUE THREAD

**Issue by dritir** [AckerApple/path-reader#5]
Hi! Would it be possible to define if a file will be added to the array based on a fs.stats comparison?

I would like a list of file paths filtered by [mtime](https://nodejs.org/api/fs.html#fs_stats_mtime) for example. Is there a way to do so in a callback?

**Comment by AckerApple** [comment]
Looking up... I think so.. One minute please

**Comment by AckerApple** [comment]
I am building you a test case for what I think you want. This will be more than I minute.

I am going to attempt to use the options.valuetizer to filter files by mtime.

Brb

**Comment by AckerApple** [comment]
First, you will need to acquire the latest version of path-reader v1.1.0

A test case has been created related to your request:
https://github.com/AckerApple/path-reader/blob/master/test/test.js#L1388

Essentially, when you ask path-reader to read you items, you pass in an option of `options.valuetizer=function(stat, fileName, filePath){}` and every item will be passed into that function. Return null if you do NOT want the item. Otherwise return what you want your end results to contain. If you return `stat` then every item in results will be the stat variable, if you return fileName, then you just get results of file names. Again, return null if you do NOT want the item in your results.

Please try it out

**Comment by AckerApple** [comment]
Your code will look something like this:
```
var options = {
  valuetizer:function(stat, shortName, longPath){
    return stat.mtime ? stat : null
  }
}

require('path-reader').promiseFiles(__dirname, 'file', options)
.then(function(results){
  console.log(results)//an array of file stat if the file has a mtime definition
})
```

**Comment by dritir** [comment]
Hi, I did some very fast test and could not make the options function work.
I changed `return stat.mtime ? stat : null` for `return null` and added a console.log('test') and it is still returning all files and not printing "test".

I have to leave now, but I will try further in a while.
Thanks for answering this fast!

**Comment by AckerApple** [comment]
Be sure you have the latest version 1.1.0 otherwise it wont work as described

**Comment by dritir** [comment]
Ok, I updated to 1.1.0 it is working accordingly! Very nice!

**Comment by AckerApple** [comment]
It is very nice, which is why I'm surprised I didn't already have the valuetizer skipping nulls. But now it does.

Please star, follow, and perform any other social actions that might naturally boost this packages popularity.

Also close this issue if satisfied
